/**
 * @file STServoYarpDriver.cpp
 * @brief YARP device plugin — ST bus servo motor control driver.
 *
 * See STServoYarpDriver.hpp for the full interface description, unit
 * conventions, and configuration reference.
 */

#include "yarp/STServoYarpDriver.hpp"

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <string>

// YARP plug-in factory boilerplate (auto-generated by yarp_prepare_plugin,
// so this source file needs no explicit registration macros).

// ---------------------------------------------------------------------------
// Log component
// ---------------------------------------------------------------------------
YARP_LOG_COMPONENT(STSERVO, "servo.st_servo")

// ---------------------------------------------------------------------------
// DeviceDriver
// ---------------------------------------------------------------------------

bool STServoYarpDriver::open(yarp::os::Searchable& config)
{
    // --- Parse required config keys ----------------------------------------
    if (!config.check("port")) {
        yCError(STSERVO) << "Missing required config key: 'port'";
        return false;
    }
    if (!config.check("baud")) {
        yCError(STSERVO) << "Missing required config key: 'baud'";
        return false;
    }
    if (!config.check("servo_ids")) {
        yCError(STSERVO) << "Missing required config key: 'servo_ids' (e.g. \"(1 2 3)\")";
        return false;
    }

    const std::string port = config.find("port").asString();
    const int         baud = config.find("baud").asInt32();
    const int    timeoutMs = config.check("timeout_ms")
                                  ? config.find("timeout_ms").asInt32()
                                  : 50;

    // --- Parse servo ID list -----------------------------------------------
    yarp::os::Bottle* idList = config.find("servo_ids").asList();
    if (!idList || idList->size() == 0) {
        yCError(STSERVO) << "'servo_ids' must be a non-empty list, e.g. \"(1 2 3)\"";
        return false;
    }

    servoIds_.clear();
    for (int i = 0; i < static_cast<int>(idList->size()); ++i) {
        const int id = idList->get(i).asInt32();
        if (id < 0 || id > 253) {
            yCError(STSERVO) << "Servo ID" << id << "is out of range [0, 253]";
            return false;
        }
        servoIds_.push_back(static_cast<uint8_t>(id));
    }

    nJoints_ = static_cast<int>(servoIds_.size());

    // --- Open serial port --------------------------------------------------
    try {
        serial_ = std::make_unique<SerialPortDriver>(port, baud, timeoutMs);
    } catch (const std::exception& e) {
        yCError(STSERVO) << "Failed to create SerialPortDriver:" << e.what();
        return false;
    }

    if (!serial_->isOpen()) {
        yCError(STSERVO) << "Could not open serial port" << port;
        serial_.reset();
        return false;
    }

    // --- Allocate per-joint state arrays -----------------------------------
    refSpeeds_        .assign(nJoints_, 60.0);   // 60 deg/s default
    refAccelerations_ .assign(nJoints_, 0.0);    // 0 → servo uses max acceleration
    refTorques_       .assign(nJoints_, 100.0);  // 100 % (unclamped)
    controlModes_     .assign(nJoints_, VOCAB_CM_POSITION);
    encoderOffsets_    .assign(nJoints_, 0.0);
    pidEnabled_       .assign(nJoints_, true);
    prevSpeedDegS_    .assign(nJoints_, 0.0);
    prevSpeedTime_    .assign(nJoints_, yarp::os::Time::now());

    // --- Verify servo presence ----------------------------------------------
    yCInfo(STSERVO) << "Pinging" << nJoints_ << "servo(s)...";
    for (int j = 0; j < nJoints_; ++j) {
        auto pkt  = STServoRequest::ping(servoIds_[j]);
        auto resp = transact(pkt, 6);
        if (!resp.valid) {
            yCWarning(STSERVO) << "No response from servo ID" << servoIds_[j]
                               << "(joint" << j << ") — check wiring / ID / baud";
        } else {
            yCInfo(STSERVO) << "  Joint" << j
                            << "  servo ID" << servoIds_[j] << "  OK"
                            << (resp.hasError() ? "  [ERROR FLAGS SET]" : "");
        }
    }

    // --- Optionally ensure servos respond to READ commands (RESPONSE_LEVEL=1) ---
    // Factory default is 0 (ping-only). Enable with: auto_response_level true
    // in the device config. Not needed when RESPONSE_LEVEL was already set.
    if (config.check("auto_response_level") &&
        config.find("auto_response_level").asBool())
    {
        for (int j = 0; j < nJoints_; ++j) {
            if (!readByte(servoIds_[j], STServo::Register::TORQUE_SWITCH)) {
                yCInfo(STSERVO) << "  Joint" << j << "servo ID" << servoIds_[j]
                                << "not responding to READ — setting RESPONSE_LEVEL=1";
                writeByte(servoIds_[j], STServo::Register::LOCK_FLAG, 0);
                writeByte(servoIds_[j], STServo::Register::RESPONSE_LEVEL, 1);
                writeByte(servoIds_[j], STServo::Register::LOCK_FLAG, 1);
            }
        }
    }

    yCInfo(STSERVO) << "st_servo driver opened on" << port
                    << "at" << baud << "baud,"
                    << nJoints_ << "joint(s)";
    return true;
}

bool STServoYarpDriver::close()
{
    if (!serial_) return true;

    // Disable all amplifiers gracefully before closing
    for (int j = 0; j < nJoints_; ++j)
        disableAmp(j);

    serial_.reset();
    yCInfo(STSERVO) << "st_servo driver closed";
    return true;
}

// ---------------------------------------------------------------------------
// Private — low-level half-duplex UART transaction helpers
// ---------------------------------------------------------------------------

STServo::ServoResponse STServoYarpDriver::transact(
    const std::vector<uint8_t>& packet,
    std::size_t                 expectedBytes) const
{
    std::lock_guard<std::mutex> lk(mutex_);
    if (!serial_ || !serial_->isOpen()) return {};
    if (!serial_->write(packet))        return {};
    auto raw = serial_->read(expectedBytes);
    return STServo::ServoResponse::parse(raw);
}

std::optional<uint8_t> STServoYarpDriver::readByte(
    uint8_t id, const STServo::Reg& reg) const
{
    auto resp = transact(STServoRequest::read(id, reg), 6 + reg.size);
    if (!resp.valid || resp.data.empty()) return std::nullopt;
    return resp.data[0];
}

std::optional<uint16_t> STServoYarpDriver::readUint16(
    uint8_t id, const STServo::Reg& reg) const
{
    auto resp = transact(STServoRequest::read(id, reg), 6 + reg.size);
    if (!resp.valid) return std::nullopt;
    return resp.asUint16(0);
}

bool STServoYarpDriver::writeByte(
    uint8_t id, const STServo::Reg& reg, uint8_t value)
{
    // RESPONSE_LEVEL = 0 (default) — no status response for writes.
    std::lock_guard<std::mutex> lk(mutex_);
    if (!serial_ || !serial_->isOpen()) return false;
    return serial_->write(STServoRequest::write(reg, id, { value }));
}

bool STServoYarpDriver::writeUint16(
    uint8_t id, const STServo::Reg& reg, uint16_t value)
{
    std::lock_guard<std::mutex> lk(mutex_);
    if (!serial_ || !serial_->isOpen()) return false;
    std::vector<uint8_t> data = {
        static_cast<uint8_t>(value & 0xFF),
        static_cast<uint8_t>((value >> 8) & 0xFF),
    };
    return serial_->write(STServoRequest::write(reg, id, data));
}

bool STServoYarpDriver::writeOperationMode(uint8_t id, uint8_t mode)
{
    // EEPROM writes require releasing the LOCK_FLAG guard first.
    // Each call to writeByte() below takes the mutex independently.
    if (!writeByte(id, STServo::Register::LOCK_FLAG, 0)) return false;
    if (!writeByte(id, STServo::Register::OPERATION_MODE, mode)) return false;
    if (!writeByte(id, STServo::Register::LOCK_FLAG, 1)) return false;
    return true;
}

bool STServoYarpDriver::doMoveOne(int j, int16_t steps, uint16_t speedSteps)
{
    if (!validJoint(j)) return false;

    // Calculate acceleration byte
    uint8_t accRaw = 0;
    if (refAccelerations_[j] > 0.0) {
        accRaw = static_cast<uint8_t>(
            std::clamp(std::round(refAccelerations_[j] * STEPS_PER_DEG / ACC_UNIT),
                       1.0, 254.0));
    }

    // 7-byte atomic write: ACCELERATION(1) | TARGET_LOCATION(2) | OPERATION_TIME(2) | OPERATION_SPEED(2)
    static constexpr STServo::Reg REG_MOVE_WITH_ACC = {
        0x29, 7, STServo::MemoryArea::SRAM, STServo::Access::RW
    };

    // Build 7-byte payload
    std::vector<uint8_t> payload;
    payload.reserve(7);
    payload.push_back(accRaw);
    auto moveData = encodeMovePayload(steps, speedSteps);
    payload.insert(payload.end(), moveData.begin(), moveData.end());

    std::lock_guard<std::mutex> lk(mutex_);
    if (!serial_ || !serial_->isOpen()) return false;
    return serial_->write(STServoRequest::write(REG_MOVE_WITH_ACC, servoIds_[j], payload));
}

bool STServoYarpDriver::doSyncMove(const std::vector<int>&     jointIdxs,
                                   const std::vector<int16_t>& stepsVec,
                                   const std::vector<uint16_t>&speedVec)
{
    if (jointIdxs.empty()) return true;

    // 7-byte atomic write: ACCELERATION(1) | TARGET_LOCATION(2) | OPERATION_TIME(2) | OPERATION_SPEED(2)
    // Registers 0x29-0x2F are consecutive, so write them all in one SYNC_WRITE
    static constexpr STServo::Reg REG_MOVE_WITH_ACC = {
        0x29, 7, STServo::MemoryArea::SRAM, STServo::Access::RW
    };

    std::vector<std::pair<uint8_t, std::vector<uint8_t>>> targets;
    targets.reserve(jointIdxs.size());

    for (std::size_t idx = 0; idx < jointIdxs.size(); ++idx) {
        int j = jointIdxs[idx];
        if (!validJoint(j)) continue;
        
        // Calculate acceleration byte
        uint8_t accRaw = 0;
        if (refAccelerations_[j] > 0.0) {
            accRaw = static_cast<uint8_t>(
                std::clamp(std::round(refAccelerations_[j] * STEPS_PER_DEG / ACC_UNIT),
                           1.0, 254.0));
        }
        
        // Build 7-byte payload: acc(1) + move_payload(6)
        std::vector<uint8_t> payload;
        payload.reserve(7);
        payload.push_back(accRaw);
        auto moveData = encodeMovePayload(stepsVec[idx], speedVec[idx]);
        payload.insert(payload.end(), moveData.begin(), moveData.end());
        
        targets.emplace_back(servoIds_[j], std::move(payload));
    }

    std::lock_guard<std::mutex> lk(mutex_);
    if (!serial_ || !serial_->isOpen()) return false;
    // SYNC_WRITE: no response from servos
    return serial_->write(STServoRequest::write(REG_MOVE_WITH_ACC, targets));
}

bool STServoYarpDriver::syncReadUint16(const STServo::Reg& reg,
                                       std::vector<uint16_t>& out) const
{
    auto pkt = STServoRequest::read(servoIds_, reg);
    std::lock_guard<std::mutex> lk(mutex_);
    if (!serial_ || !serial_->isOpen()) return false;
    if (!serial_->write(pkt)) return false;

    out.assign(nJoints_, 0);
    bool ok = true;
    const std::size_t respSz = 6 + reg.size;

    for (int i = 0; i < nJoints_; ++i) {
        auto raw  = serial_->read(respSz);
        auto resp = STServo::ServoResponse::parse(raw);
        if (!resp.valid) {
            ok = false;
            continue;
        }
        if (auto v = resp.asUint16(0)) {
            out[i] = *v;
        } else {
            ok = false;
        }
    }
    return ok;
}

bool STServoYarpDriver::syncReadByte(const STServo::Reg& reg,
                                     std::vector<uint8_t>& out) const
{
    auto pkt = STServoRequest::read(servoIds_, reg);
    std::lock_guard<std::mutex> lk(mutex_);
    if (!serial_ || !serial_->isOpen()) return false;
    if (!serial_->write(pkt)) return false;

    out.assign(nJoints_, 0);
    bool ok = true;
    const std::size_t respSz = 6 + reg.size;

    for (int i = 0; i < nJoints_; ++i) {
        auto raw  = serial_->read(respSz);
        auto resp = STServo::ServoResponse::parse(raw);
        if (!resp.valid || resp.data.empty()) {
            ok = false;
            continue;
        }
        out[i] = resp.data[0];
    }
    return ok;
}

// ---------------------------------------------------------------------------
// IPositionControl
// ---------------------------------------------------------------------------

bool STServoYarpDriver::getAxes(int* ax)
{
    if (!ax) return false;
    *ax = nJoints_;
    return true;
}

bool STServoYarpDriver::positionMove(int j, double ref)
{
    if (!validJoint(j)) return false;
    
    // Ensure servo is in position mode (OPERATION_MODE=0)
    if (controlModes_[j] != VOCAB_CM_POSITION) {
        if (!writeOperationMode(servoIds_[j], 0)) return false;
        controlModes_[j] = VOCAB_CM_POSITION;
    }
    
    double target = ref - encoderOffsets_[j];
    return doMoveOne(j, degToSteps(target), degSToStepS(refSpeeds_[j]));
}

bool STServoYarpDriver::positionMove(const double* refs)
{
    if (!refs) return false;
    
    // Ensure all servos are in position mode (OPERATION_MODE=0)
    for (int j = 0; j < nJoints_; ++j) {
        if (controlModes_[j] != VOCAB_CM_POSITION) {
            if (!writeOperationMode(servoIds_[j], 0)) return false;
            controlModes_[j] = VOCAB_CM_POSITION;
        }
    }
    
    std::vector<int>      idxs(nJoints_);
    std::vector<int16_t>  steps(nJoints_);
    std::vector<uint16_t> speeds(nJoints_);
    for (int j = 0; j < nJoints_; ++j) {
        idxs[j]   = j;
        steps[j]  = degToSteps(refs[j] - encoderOffsets_[j]);
        speeds[j] = degSToStepS(refSpeeds_[j]);
    }
    return doSyncMove(idxs, steps, speeds);
}

bool STServoYarpDriver::positionMove(int n_joint, const int* joints,
                                     const double* refs)
{
    if (!joints || !refs) return false;
    
    // Ensure specified servos are in position mode (OPERATION_MODE=0)
    for (int i = 0; i < n_joint; ++i) {
        int j = joints[i];
        if (!validJoint(j)) return false;
        if (controlModes_[j] != VOCAB_CM_POSITION) {
            if (!writeOperationMode(servoIds_[j], 0)) return false;
            controlModes_[j] = VOCAB_CM_POSITION;
        }
    }
    
    std::vector<int>      idxs(n_joint);
    std::vector<int16_t>  steps(n_joint);
    std::vector<uint16_t> speeds(n_joint);
    for (int i = 0; i < n_joint; ++i) {
        idxs[i]   = joints[i];
        steps[i]  = degToSteps(refs[i] - encoderOffsets_[joints[i]]);
        speeds[i] = degSToStepS(refSpeeds_[joints[i]]);
    }
    return doSyncMove(idxs, steps, speeds);
}

bool STServoYarpDriver::relativeMove(int j, double delta)
{
    double current = 0.0;
    if (!getEncoder(j, &current)) return false;
    return positionMove(j, current + delta);
}

bool STServoYarpDriver::relativeMove(const double* deltas)
{
    if (!deltas) return false;
    std::vector<double> encs(nJoints_);
    if (!getEncoders(encs.data())) return false;
    std::vector<double> targets(nJoints_);
    for (int j = 0; j < nJoints_; ++j)
        targets[j] = encs[j] + deltas[j];
    return positionMove(targets.data());
}

bool STServoYarpDriver::relativeMove(int n_joint, const int* joints,
                                     const double* deltas)
{
    if (!joints || !deltas) return false;
    std::vector<double> targets(n_joint);
    for (int i = 0; i < n_joint; ++i) {
        double enc = 0.0;
        getEncoder(joints[i], &enc);
        targets[i] = enc + deltas[i];
    }
    return positionMove(n_joint, joints, targets.data());
}

bool STServoYarpDriver::checkMotionDone(int j, bool* flag)
{
    if (!validJoint(j) || !flag) return false;
    auto val = readByte(servoIds_[j], STServo::Register::MOVE_FLAG);
    if (!val) return false;
    *flag = (*val == 0);  // 0 = stopped, 1 = moving
    return true;
}

bool STServoYarpDriver::checkMotionDone(bool* flag)
{
    if (!flag) return false;
    std::vector<uint8_t> signs;
    if (!syncReadByte(STServo::Register::MOVE_FLAG, signs)) return false;
    *flag = std::all_of(signs.begin(), signs.end(),
                        [](uint8_t s) { return s == 0; });
    return true;
}

bool STServoYarpDriver::checkMotionDone(int n_joint, const int* joints,
                                        bool* flag)
{
    if (!joints || !flag) return false;
    *flag = true;
    for (int i = 0; i < n_joint; ++i) {
        bool done = false;
        if (!checkMotionDone(joints[i], &done)) return false;
        if (!done) { *flag = false; break; }
    }
    return true;
}

bool STServoYarpDriver::setRefSpeed(int j, double sp)
{
    if (!validJoint(j)) return false;
    refSpeeds_[j] = std::max(0.0, sp);
    return true;
}

bool STServoYarpDriver::setRefSpeeds(const double* spds)
{
    if (!spds) return false;
    for (int j = 0; j < nJoints_; ++j)
        refSpeeds_[j] = std::max(0.0, spds[j]);
    return true;
}

bool STServoYarpDriver::setRefSpeeds(int n_joint, const int* joints,
                                     const double* spds)
{
    if (!joints || !spds) return false;
    for (int i = 0; i < n_joint; ++i)
        if (validJoint(joints[i]))
            refSpeeds_[joints[i]] = std::max(0.0, spds[i]);
    return true;
}

bool STServoYarpDriver::setRefAcceleration(int j, double acc)
{
    if (!validJoint(j)) return false;
    refAccelerations_[j] = std::max(0.0, acc);
    return true;
}

bool STServoYarpDriver::setRefAccelerations(const double* accs)
{
    if (!accs) return false;
    for (int j = 0; j < nJoints_; ++j)
        refAccelerations_[j] = std::max(0.0, accs[j]);
    return true;
}

bool STServoYarpDriver::setRefAccelerations(int n_joint, const int* joints,
                                            const double* accs)
{
    if (!joints || !accs) return false;
    for (int i = 0; i < n_joint; ++i)
        if (validJoint(joints[i]))
            refAccelerations_[joints[i]] = std::max(0.0, accs[i]);
    return true;
}

bool STServoYarpDriver::getRefSpeed(int j, double* ref)
{
    if (!validJoint(j) || !ref) return false;
    *ref = refSpeeds_[j];
    return true;
}

bool STServoYarpDriver::getRefSpeeds(double* spds)
{
    if (!spds) return false;
    std::copy(refSpeeds_.begin(), refSpeeds_.end(), spds);
    return true;
}

bool STServoYarpDriver::getRefSpeeds(int n_joint, const int* joints,
                                     double* spds)
{
    if (!joints || !spds) return false;
    for (int i = 0; i < n_joint; ++i)
        if (validJoint(joints[i]))
            spds[i] = refSpeeds_[joints[i]];
    return true;
}

bool STServoYarpDriver::getRefAcceleration(int j, double* acc)
{
    if (!validJoint(j) || !acc) return false;
    *acc = refAccelerations_[j];
    return true;
}

bool STServoYarpDriver::getRefAccelerations(double* accs)
{
    if (!accs) return false;
    std::copy(refAccelerations_.begin(), refAccelerations_.end(), accs);
    return true;
}

bool STServoYarpDriver::getRefAccelerations(int n_joint, const int* joints,
                                            double* accs)
{
    if (!joints || !accs) return false;
    for (int i = 0; i < n_joint; ++i)
        if (validJoint(joints[i]))
            accs[i] = refAccelerations_[joints[i]];
    return true;
}

bool STServoYarpDriver::stop(int j)
{
    if (!validJoint(j)) return false;
    // Setting OPERATION_SPEED to 0 stops motion without disabling the servo
    return writeUint16(servoIds_[j], STServo::Register::OPERATION_SPEED, 0);
}

bool STServoYarpDriver::stop()
{
    // SYNC_WRITE speed = 0 to all servos
    static constexpr STServo::Reg REG_SPEED = STServo::Register::OPERATION_SPEED;
    std::vector<std::pair<uint8_t, std::vector<uint8_t>>> targets;
    targets.reserve(nJoints_);
    for (int j = 0; j < nJoints_; ++j)
        targets.emplace_back(servoIds_[j], std::vector<uint8_t>{0x00, 0x00});
    std::lock_guard<std::mutex> lk(mutex_);
    if (!serial_ || !serial_->isOpen()) return false;
    return serial_->write(STServoRequest::write(REG_SPEED, targets));
}

bool STServoYarpDriver::stop(int n_joint, const int* joints)
{
    if (!joints) return false;
    bool ok = true;
    for (int i = 0; i < n_joint; ++i)
        if (!stop(joints[i])) ok = false;
    return ok;
}

// ---------------------------------------------------------------------------
// IVelocityControl
// ---------------------------------------------------------------------------

bool STServoYarpDriver::velocityMove(int j, double sp)
{
    if (!validJoint(j)) return false;

    // Ensure the servo is in constant-speed mode (OPERATION_MODE=1)
    if (controlModes_[j] != VOCAB_CM_VELOCITY) {
        if (!writeOperationMode(servoIds_[j], 1)) return false;
        controlModes_[j] = VOCAB_CM_VELOCITY;
    }

    uint16_t rawSpeed = degSToStepS(sp);

    // In mode 1, a non-zero OPERATION_SPEED sets the rotation velocity.
    // The servo uses the sign via TORQUE_SWITCH bit or the direction is set
    // by the sign of the TARGET_LOCATION relative move. Here we write speed
    // directly and note that direction encoding varies per firmware revision.
    return writeUint16(servoIds_[j], STServo::Register::OPERATION_SPEED, rawSpeed);
}

bool STServoYarpDriver::velocityMove(const double* sp)
{
    if (!sp) return false;
    bool ok = true;
    for (int j = 0; j < nJoints_; ++j)
        if (!velocityMove(j, sp[j])) ok = false;
    return ok;
}

bool STServoYarpDriver::velocityMove(int n_joint, const int* joints,
                                     const double* spds)
{
    if (!joints || !spds) return false;
    bool ok = true;
    for (int i = 0; i < n_joint; ++i)
        if (!velocityMove(joints[i], spds[i])) ok = false;
    return ok;
}

// ---------------------------------------------------------------------------
// ITorqueControl
// @note Torque control is approximated — ST servos have no torque sensor.
//       setRefTorque writes TORQUE_LIMIT (a max-torque clamp, not a setpoint).
//       getTorque returns CURRENT_LOAD (drive duty cycle) as a proxy.
// ---------------------------------------------------------------------------

bool STServoYarpDriver::getRefTorques(double* t)
{
    if (!t) return false;
    std::copy(refTorques_.begin(), refTorques_.end(), t);
    return true;
}

bool STServoYarpDriver::getRefTorque(int j, double* t)
{
    if (!validJoint(j) || !t) return false;
    *t = refTorques_[j];
    return true;
}

bool STServoYarpDriver::setRefTorques(const double* t)
{
    if (!t) return false;
    bool ok = true;
    for (int j = 0; j < nJoints_; ++j)
        if (!setRefTorque(j, t[j])) ok = false;
    return ok;
}

bool STServoYarpDriver::setRefTorque(int j, double t)
{
    if (!validJoint(j)) return false;
    // Clamp to [0, 100] % then scale to register range [0, 1000] (1 % per count)
    t = std::clamp(t, 0.0, 100.0);
    refTorques_[j] = t;
    uint16_t raw = static_cast<uint16_t>(std::round(t * 10.0));
    return writeUint16(servoIds_[j], STServo::Register::TORQUE_LIMIT, raw);
}

bool STServoYarpDriver::getTorque(int j, double* t)
{
    if (!validJoint(j) || !t) return false;
    // CURRENT_LOAD units: 0.1 %, range 0–1000 → map to 0–100 %
    auto val = readUint16(servoIds_[j], STServo::Register::CURRENT_LOAD);
    if (!val) return false;
    *t = *val * LOAD_SCALE;
    return true;
}

bool STServoYarpDriver::getTorques(double* t)
{
    if (!t) return false;
    std::vector<uint16_t> raw;
    if (!syncReadUint16(STServo::Register::CURRENT_LOAD, raw)) return false;
    for (int j = 0; j < nJoints_; ++j)
        t[j] = raw[j] * LOAD_SCALE;
    return true;
}

bool STServoYarpDriver::getTorqueRange(int j, double* min, double* max)
{
    if (!validJoint(j) || !min || !max) return false;
    *min = 0.0;
    // MAX_TORQUE EEPROM register: units 0.1 %, range 0–1000
    auto val = readUint16(servoIds_[j], STServo::Register::MAX_TORQUE);
    *max = val ? (*val * LOAD_SCALE) : 100.0;
    return true;
}

bool STServoYarpDriver::getTorqueRanges(double* min, double* max)
{
    if (!min || !max) return false;
    bool ok = true;
    for (int j = 0; j < nJoints_; ++j)
        if (!getTorqueRange(j, &min[j], &max[j])) ok = false;
    return ok;
}

// ---------------------------------------------------------------------------
// IEncoders
// ---------------------------------------------------------------------------

bool STServoYarpDriver::resetEncoder(int j)
{
    if (!validJoint(j)) return false;
    // Store the current hardware position as the new zero offset
    double current = 0.0;
    double enc     = 0.0;
    auto   raw     = readUint16(servoIds_[j], STServo::Register::CURRENT_LOCATION);
    if (!raw) return false;
    enc = stepsToDeg(static_cast<int16_t>(*raw));
    encoderOffsets_[j] = enc;  // offset = current hardware position
    return true;
}

bool STServoYarpDriver::resetEncoders()
{
    std::vector<uint16_t> raw;
    if (!syncReadUint16(STServo::Register::CURRENT_LOCATION, raw)) return false;
    for (int j = 0; j < nJoints_; ++j)
        encoderOffsets_[j] = stepsToDeg(static_cast<int16_t>(raw[j]));
    return true;
}

bool STServoYarpDriver::setEncoder(int j, double val)
{
    if (!validJoint(j)) return false;
    auto raw = readUint16(servoIds_[j], STServo::Register::CURRENT_LOCATION);
    if (!raw) return false;
    double hw = stepsToDeg(static_cast<int16_t>(*raw));
    encoderOffsets_[j] = hw - val;
    return true;
}

bool STServoYarpDriver::setEncoders(const double* vals)
{
    if (!vals) return false;
    std::vector<uint16_t> raw;
    if (!syncReadUint16(STServo::Register::CURRENT_LOCATION, raw)) return false;
    for (int j = 0; j < nJoints_; ++j) {
        double hw = stepsToDeg(static_cast<int16_t>(raw[j]));
        encoderOffsets_[j] = hw - vals[j];
    }
    return true;
}

bool STServoYarpDriver::getEncoder(int j, double* v)
{
    if (!validJoint(j) || !v) return false;
    auto raw = readUint16(servoIds_[j], STServo::Register::CURRENT_LOCATION);
    if (!raw) return false;
    *v = stepsToDeg(static_cast<int16_t>(*raw)) - encoderOffsets_[j];
    return true;
}

bool STServoYarpDriver::getEncoders(double* encs)
{
    if (!encs) return false;
    std::vector<uint16_t> raw;
    if (!syncReadUint16(STServo::Register::CURRENT_LOCATION, raw)) return false;
    for (int j = 0; j < nJoints_; ++j)
        encs[j] = stepsToDeg(static_cast<int16_t>(raw[j])) - encoderOffsets_[j];
    return true;
}

bool STServoYarpDriver::getEncoderSpeed(int j, double* sp)
{
    if (!validJoint(j) || !sp) return false;
    auto raw = readUint16(servoIds_[j], STServo::Register::CURRENT_SPEED);
    if (!raw) return false;
    double speedDegS = stepSToDegS(static_cast<uint16_t>(*raw));

    // Store for acceleration estimation
    double now = yarp::os::Time::now();
    double dt  = now - prevSpeedTime_[j];
    if (dt > 0.0)
        prevSpeedDegS_[j] = speedDegS;
    prevSpeedTime_[j] = now;

    *sp = speedDegS;
    return true;
}

bool STServoYarpDriver::getEncoderSpeeds(double* spds)
{
    if (!spds) return false;
    std::vector<uint16_t> raw;
    if (!syncReadUint16(STServo::Register::CURRENT_SPEED, raw)) return false;
    double now = yarp::os::Time::now();
    for (int j = 0; j < nJoints_; ++j) {
        double sp = stepSToDegS(raw[j]);
        prevSpeedDegS_[j] = sp;
        prevSpeedTime_[j] = now;
        spds[j] = sp;
    }
    return true;
}

bool STServoYarpDriver::getEncoderAcceleration(int j, double* acc)
{
    // Acceleration is estimated via finite-difference of two speed reads
    if (!validJoint(j) || !acc) return false;
    double prevSp   = prevSpeedDegS_[j];
    double prevTime = prevSpeedTime_[j];

    double currSp = 0.0;
    auto raw = readUint16(servoIds_[j], STServo::Register::CURRENT_SPEED);
    if (!raw) return false;
    currSp = stepSToDegS(*raw);

    double now = yarp::os::Time::now();
    double dt  = now - prevTime;

    *acc = (dt > 1e-6) ? (currSp - prevSp) / dt : 0.0;

    prevSpeedDegS_[j] = currSp;
    prevSpeedTime_[j] = now;
    return true;
}

bool STServoYarpDriver::getEncoderAccelerations(double* accs)
{
    if (!accs) return false;
    bool ok = true;
    for (int j = 0; j < nJoints_; ++j)
        if (!getEncoderAcceleration(j, &accs[j])) ok = false;
    return ok;
}

bool STServoYarpDriver::getEncoderTimed(int j, double* v, double* t)
{
    if (!getEncoder(j, v)) return false;
    if (t) *t = yarp::os::Time::now();
    return true;
}

bool STServoYarpDriver::getEncodersTimed(double* encs, double* ts)
{
    if (!getEncoders(encs)) return false;
    double now = yarp::os::Time::now();
    if (ts)
        for (int j = 0; j < nJoints_; ++j)
            ts[j] = now;
    return true;
}

// ---------------------------------------------------------------------------
// IMotorEncoders  (direct-drive — identical to joint encoders)
// ---------------------------------------------------------------------------

bool STServoYarpDriver::getNumberOfMotorEncoders(int* num)
{
    if (!num) return false;
    *num = nJoints_;
    return true;
}

bool STServoYarpDriver::resetMotorEncoder(int m)       { return resetEncoder(m);    }
bool STServoYarpDriver::resetMotorEncoders()           { return resetEncoders();    }

bool STServoYarpDriver::setMotorEncoderCountsPerRevolution(int m, const double /*cpr*/)
{
    // CPR is fixed by hardware (4096); silently succeed to avoid breaking callers
    return validJoint(m);
}

bool STServoYarpDriver::getMotorEncoderCountsPerRevolution(int m, double* cpr)
{
    if (!validJoint(m) || !cpr) return false;
    *cpr = MOTOR_CPR;
    return true;
}

bool STServoYarpDriver::setMotorEncoder(int m, double val)   { return setEncoder(m, val);    }
bool STServoYarpDriver::setMotorEncoders(const double* vals) { return setEncoders(vals);      }
bool STServoYarpDriver::getMotorEncoder(int m, double* v)    { return getEncoder(m, v);       }
bool STServoYarpDriver::getMotorEncoders(double* encs)        { return getEncoders(encs);      }

bool STServoYarpDriver::getMotorEncodersTimed(double* encs, double* times)
{
    if (!encs || !times) return false;
    double ts = yarp::os::Time::now();
    if (!getEncoders(encs)) return false;
    std::fill(times, times + nJoints_, ts);
    return true;
}

bool STServoYarpDriver::getMotorEncoderTimed(int m, double* enc, double* time)
{
    if (!enc || !time) return false;
    *time = yarp::os::Time::now();
    return getEncoder(m, enc);
}

bool STServoYarpDriver::getMotorEncoderSpeed(int m, double* sp)
{
    return getEncoderSpeed(m, sp);
}

bool STServoYarpDriver::getMotorEncoderSpeeds(double* spds)
{
    return getEncoderSpeeds(spds);
}

bool STServoYarpDriver::getMotorEncoderAcceleration(int m, double* acc)
{
    return getEncoderAcceleration(m, acc);
}

bool STServoYarpDriver::getMotorEncoderAccelerations(double* accs)
{
    return getEncoderAccelerations(accs);
}

// ---------------------------------------------------------------------------
// IControlMode
// ---------------------------------------------------------------------------

bool STServoYarpDriver::getControlMode(int j, int* mode)
{
    if (!validJoint(j) || !mode) return false;
    *mode = controlModes_[j];
    return true;
}

bool STServoYarpDriver::getControlModes(int* modes)
{
    if (!modes) return false;
    std::copy(controlModes_.begin(), controlModes_.end(), modes);
    return true;
}

bool STServoYarpDriver::getControlModes(int n_joint, const int* joints,
                                        int* modes)
{
    if (!joints || !modes) return false;
    for (int i = 0; i < n_joint; ++i)
        if (validJoint(joints[i]))
            modes[i] = controlModes_[joints[i]];
    return true;
}

bool STServoYarpDriver::setControlMode(const int j, const int mode)
{
    if (!validJoint(j)) return false;

    switch (mode) {
        case VOCAB_CM_POSITION:
            if (!writeOperationMode(servoIds_[j], 0)) return false;
            break;
        case VOCAB_CM_VELOCITY:
            if (!writeOperationMode(servoIds_[j], 1)) return false;
            break;
        case VOCAB_CM_PWM:
            if (!writeOperationMode(servoIds_[j], 2)) return false;
            break;
        case VOCAB_CM_TORQUE:
            // No dedicated torque mode on ST servos; keep current HW mode,
            // but accept the YARP mode for setRefTorque calls.
            break;
        case VOCAB_CM_IDLE:
            if (!writeByte(servoIds_[j], STServo::Register::TORQUE_SWITCH, 0))
                return false;
            break;
        default:
            yCWarning(STSERVO) << "setControlMode: unsupported mode" << mode
                               << "for joint" << j;
            return false;
    }

    controlModes_[j] = mode;
    return true;
}

bool STServoYarpDriver::setControlModes(int n_joint, const int* joints,
                                        int* modes)
{
    if (!joints || !modes) return false;
    bool ok = true;
    for (int i = 0; i < n_joint; ++i)
        if (!setControlMode(joints[i], modes[i])) ok = false;
    return ok;
}

bool STServoYarpDriver::setControlModes(int* modes)
{
    if (!modes) return false;
    bool ok = true;
    for (int j = 0; j < nJoints_; ++j)
        if (!setControlMode(j, modes[j])) ok = false;
    return ok;
}

// ---------------------------------------------------------------------------
// IAmplifierControl
// ---------------------------------------------------------------------------

bool STServoYarpDriver::enableAmp(int j)
{
    if (!validJoint(j)) return false;
    return writeByte(servoIds_[j], STServo::Register::TORQUE_SWITCH, 1);
}

bool STServoYarpDriver::disableAmp(int j)
{
    if (!validJoint(j)) return false;
    return writeByte(servoIds_[j], STServo::Register::TORQUE_SWITCH, 0);
}

bool STServoYarpDriver::getAmpStatus(int* st)
{
    if (!st) return false;
    for (int j = 0; j < nJoints_; ++j) {
        auto raw = readByte(servoIds_[j], STServo::Register::SERVO_STATUS);
        st[j] = raw ? static_cast<int>(*raw) : -1;
    }
    return true;
}

bool STServoYarpDriver::getAmpStatus(int j, int* v)
{
    if (!validJoint(j) || !v) return false;
    auto raw = readByte(servoIds_[j], STServo::Register::SERVO_STATUS);
    if (!raw) return false;
    *v = static_cast<int>(*raw);
    return true;
}

bool STServoYarpDriver::getCurrents(double* vals)
{
    if (!vals) return false;
    std::vector<uint16_t> raw;
    if (!syncReadUint16(STServo::Register::CURRENT_CURRENT, raw)) return false;
    for (int j = 0; j < nJoints_; ++j)
        vals[j] = raw[j] * CURRENT_SCALE;
    return true;
}

bool STServoYarpDriver::getCurrent(int j, double* val)
{
    if (!validJoint(j) || !val) return false;
    auto raw = readUint16(servoIds_[j], STServo::Register::CURRENT_CURRENT);
    if (!raw) return false;
    *val = *raw * CURRENT_SCALE;
    return true;
}

bool STServoYarpDriver::getMaxCurrent(int j, double* v)
{
    if (!validJoint(j) || !v) return false;
    // TORQUE_LIMIT (SRAM) gives the active torque ceiling. Proxy via PROTECTION_CURRENT
    // (EEPROM) which is in counts × 6.5 mA.
    auto raw = readUint16(servoIds_[j], STServo::Register::PROTECTION_CURRENT);
    if (!raw) return false;
    *v = *raw * CURRENT_SCALE;
    return true;
}

bool STServoYarpDriver::setMaxCurrent(int j, double v)
{
    if (!validJoint(j)) return false;
    // Write to TORQUE_LIMIT (SRAM) for immediate effect; 1 count = 0.1 % of rated torque.
    // We approximate: max current → torque %, then write TORQUE_LIMIT.
    // For a calibration-free driver we simply map amperes to steps as:
    //   raw = A / CURRENT_SCALE, clamped to [0, 511] for PROTECTION_CURRENT range.
    uint16_t rawCounts = static_cast<uint16_t>(
        std::clamp(std::round(v / CURRENT_SCALE), 0.0, 511.0));
    return writeUint16(servoIds_[j], STServo::Register::PROTECTION_CURRENT, rawCounts);
}

bool STServoYarpDriver::getPowerSupplyVoltage(int j, double* v)
{
    if (!validJoint(j) || !v) return false;
    auto raw = readByte(servoIds_[j], STServo::Register::CURRENT_VOLTAGE);
    if (!raw) return false;
    *v = *raw * VOLTAGE_SCALE;
    return true;
}

// ---------------------------------------------------------------------------
// IPidControl
// Servo PID registers are EEPROM (persistent) with uint8 range [0, 254].
// ---------------------------------------------------------------------------

namespace {
    /// Clamp a Pid coefficient to the servo's [0, 254] uint8 register range.
    inline uint8_t clampPidCoeff(double v)
    {
        return static_cast<uint8_t>(std::clamp(std::round(v), 0.0, 254.0));
    }
} // namespace

bool STServoYarpDriver::setPid(const yarp::dev::PidControlTypeEnum& pidtype,
                               int j, const yarp::dev::Pid& pid)
{
    if (!validJoint(j)) return false;
    uint8_t id = servoIds_[j];

    if (pidtype == yarp::dev::VOCAB_PIDTYPE_POSITION) {
        if (!writeByte(id, STServo::Register::P_COEFF, clampPidCoeff(pid.kp))) return false;
        if (!writeByte(id, STServo::Register::I_COEFF, clampPidCoeff(pid.ki))) return false;
        if (!writeByte(id, STServo::Register::D_COEFF, clampPidCoeff(pid.kd))) return false;
    } else if (pidtype == yarp::dev::VOCAB_PIDTYPE_VELOCITY) {
        if (!writeByte(id, STServo::Register::SPEED_P_COEFF,   clampPidCoeff(pid.kp))) return false;
        if (!writeByte(id, STServo::Register::VELOCITY_I_COEFF, clampPidCoeff(pid.ki))) return false;
    } else {
        yCWarning(STSERVO) << "setPid: pid type" << static_cast<int>(pidtype)
                           << "not supported by ST servo hardware";
        return false;
    }
    return true;
}

bool STServoYarpDriver::setPids(const yarp::dev::PidControlTypeEnum& pidtype,
                                const yarp::dev::Pid* pids)
{
    if (!pids) return false;
    bool ok = true;
    for (int j = 0; j < nJoints_; ++j)
        if (!setPid(pidtype, j, pids[j])) ok = false;
    return ok;
}

bool STServoYarpDriver::getPid(const yarp::dev::PidControlTypeEnum& pidtype,
                               int j, yarp::dev::Pid* pid)
{
    if (!validJoint(j) || !pid) return false;
    uint8_t id = servoIds_[j];
    *pid = yarp::dev::Pid{};

    if (pidtype == yarp::dev::VOCAB_PIDTYPE_POSITION) {
        auto p = readByte(id, STServo::Register::P_COEFF);
        auto i = readByte(id, STServo::Register::I_COEFF);
        auto d = readByte(id, STServo::Register::D_COEFF);
        if (!p || !i || !d) return false;
        pid->kp = static_cast<double>(*p);
        pid->ki = static_cast<double>(*i);
        pid->kd = static_cast<double>(*d);
    } else if (pidtype == yarp::dev::VOCAB_PIDTYPE_VELOCITY) {
        auto p = readByte(id, STServo::Register::SPEED_P_COEFF);
        auto i = readByte(id, STServo::Register::VELOCITY_I_COEFF);
        if (!p || !i) return false;
        pid->kp = static_cast<double>(*p);
        pid->ki = static_cast<double>(*i);
        pid->kd = 0.0;
    } else {
        return false;
    }
    return true;
}

bool STServoYarpDriver::getPids(const yarp::dev::PidControlTypeEnum& pidtype,
                                yarp::dev::Pid* pids)
{
    if (!pids) return false;
    bool ok = true;
    for (int j = 0; j < nJoints_; ++j)
        if (!getPid(pidtype, j, &pids[j])) ok = false;
    return ok;
}

// Reference tracking — servo drives the reference on every positionMove/velocityMove call,
// so we store references in the cached arrays and return them.

bool STServoYarpDriver::setPidReference(const yarp::dev::PidControlTypeEnum& pidtype,
                                        int j, double ref)
{
    if (!validJoint(j)) return false;
    if (pidtype == yarp::dev::VOCAB_PIDTYPE_POSITION)
        return positionMove(j, ref);
    if (pidtype == yarp::dev::VOCAB_PIDTYPE_VELOCITY)
        return velocityMove(j, ref);
    return false;
}

bool STServoYarpDriver::setPidReferences(const yarp::dev::PidControlTypeEnum& pidtype,
                                         const double* refs)
{
    if (!refs) return false;
    if (pidtype == yarp::dev::VOCAB_PIDTYPE_POSITION)
        return positionMove(refs);
    if (pidtype == yarp::dev::VOCAB_PIDTYPE_VELOCITY)
        return velocityMove(refs);
    return false;
}

bool STServoYarpDriver::setPidErrorLimit(const yarp::dev::PidControlTypeEnum& /*pidtype*/,
                                         int /*j*/, double /*limit*/)
{
    // Not directly configurable on ST servos
    return true;
}

bool STServoYarpDriver::setPidErrorLimits(const yarp::dev::PidControlTypeEnum& /*pidtype*/,
                                          const double* /*limits*/)
{
    return true;
}

bool STServoYarpDriver::getPidError(const yarp::dev::PidControlTypeEnum& pidtype,
                                    int j, double* err)
{
    if (!validJoint(j) || !err) return false;
    if (pidtype == yarp::dev::VOCAB_PIDTYPE_POSITION) {
        // Error = target - current (we don't store target per-joint, so read current only)
        *err = 0.0;
        return true;
    }
    *err = 0.0;
    return true;
}

bool STServoYarpDriver::getPidErrors(const yarp::dev::PidControlTypeEnum& pidtype,
                                     double* errs)
{
    if (!errs) return false;
    std::fill(errs, errs + nJoints_, 0.0);
    return true;
}

bool STServoYarpDriver::getPidOutput(const yarp::dev::PidControlTypeEnum& pidtype,
                                     int j, double* out)
{
    // Output proxy: CURRENT_LOAD (drive duty cycle %)
    return getTorque(j, out);
}

bool STServoYarpDriver::getPidOutputs(const yarp::dev::PidControlTypeEnum& pidtype,
                                      double* outs)
{
    return getTorques(outs);
}

bool STServoYarpDriver::getPidReference(const yarp::dev::PidControlTypeEnum& pidtype,
                                        int j, double* ref)
{
    if (!validJoint(j) || !ref) return false;
    if (pidtype == yarp::dev::VOCAB_PIDTYPE_VELOCITY) {
        *ref = refSpeeds_[j];
        return true;
    }
    // For position, read back the current target (best we can do is return current pos)
    return getEncoder(j, ref);
}

bool STServoYarpDriver::getPidReferences(const yarp::dev::PidControlTypeEnum& pidtype,
                                         double* refs)
{
    if (!refs) return false;
    if (pidtype == yarp::dev::VOCAB_PIDTYPE_VELOCITY) {
        std::copy(refSpeeds_.begin(), refSpeeds_.end(), refs);
        return true;
    }
    return getEncoders(refs);
}

bool STServoYarpDriver::getPidErrorLimit(const yarp::dev::PidControlTypeEnum& /*pidtype*/,
                                         int /*j*/, double* limit)
{
    if (limit) *limit = std::numeric_limits<double>::max();
    return true;
}

bool STServoYarpDriver::getPidErrorLimits(const yarp::dev::PidControlTypeEnum& /*pidtype*/,
                                          double* limits)
{
    if (!limits) return false;
    std::fill(limits, limits + nJoints_, std::numeric_limits<double>::max());
    return true;
}

bool STServoYarpDriver::resetPid(const yarp::dev::PidControlTypeEnum& pidtype, int j)
{
    // Set current position as target → zero the positional error
    if (!validJoint(j)) return false;
    double enc = 0.0;
    if (!getEncoder(j, &enc)) return false;
    if (pidtype == yarp::dev::VOCAB_PIDTYPE_POSITION)
        return positionMove(j, enc);
    return true;
}

bool STServoYarpDriver::disablePid(const yarp::dev::PidControlTypeEnum& /*pidtype*/,
                                    int j)
{
    // Disable torque output as the closest hardware equivalent
    if (!validJoint(j)) return false;
    pidEnabled_[j] = false;
    return disableAmp(j);
}

bool STServoYarpDriver::enablePid(const yarp::dev::PidControlTypeEnum& /*pidtype*/,
                                   int j)
{
    if (!validJoint(j)) return false;
    pidEnabled_[j] = true;
    return enableAmp(j);
}

bool STServoYarpDriver::setPidOffset(const yarp::dev::PidControlTypeEnum& /*pidtype*/,
                                      int /*j*/, double /*v*/)
{
    // Feed-forward offset not directly mappable; silently succeed
    return true;
}

bool STServoYarpDriver::isPidEnabled(const yarp::dev::PidControlTypeEnum& /*pidtype*/,
                                      int j, bool* enabled)
{
    if (!validJoint(j) || !enabled) return false;
    *enabled = pidEnabled_[j];
    return true;
}
